<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Authenticates admin panel requests using the signed token
 * generated by AdminAuthController::login().
 *
 * The Vue admin stores the token in sessionStorage and sends it
 * in the Authorization header: Bearer <token>
 */
class AdminAuth
{
    public function handle(Request $request, Closure $next): Response
    {
        $token = $request->bearerToken();

        if (empty($token)) {
            return response()->json(['error' => 'Unauthorized — no token provided.'], 401);
        }

        $adminEmail    = config('app.admin_email');
        $expectedToken = hash('sha256', $adminEmail . '|' . config('app.key') . '|' . now()->toDateString());

        if ($token !== $expectedToken) {
            return response()->json(['error' => 'Unauthorized — invalid or expired token.'], 401);
        }

        return $next($request);
    }
}
